#!/usr/bin/python
# -*- coding: utf-8 -*-
# http://beonit2.tistory.com/49
# s-han.lee@samsung.com
# daum dictionary --pretty
 
def daumDict(word):
    import urllib2
    import re
    url = "http://small.dic.daum.net/search.do?q="+ word +"&dic=eng"
    try:
        source = urllib2.urlopen(url).read()
    except:
        print "load webpage fail. check your internet connection."
        return
 
    p = re.compile(r'<div class="wrap_meaning">(.*)</div>')
    m = p.search(source)
    try:
        print m.group(1).replace("&nbsp;", " ")
    except:
        print "cannot found " + word
 
import sys
import getopt
if __name__ == "__main__":
    if len(sys.argv) is 1:
        print "insucfficient args"
        sys.exit(1)
    word = sys.argv[1]
    daumDict( word )
